### ISSUE TITLE
Minted package error

### ISSUE THREAD

**Issue by albiboni** [dzwaneveld/tudelft-report-thesis-template#1]
I had to remove the mint package because it was causing an error. I'm using TeXstudio with xelatex engine

**Comment by dzwaneveld** [comment]
Thanks for letting me know!

The `minted` package uses Pygments to highlight the code, requiring a Python installation and a shell escape to function (As can also be found in the [documentation](http://mirrors.ctan.org/macros/latex/contrib/minted/minted.pdf)). 

Although most will be using this template using Overleaf (which works out of the box with `minted`),  it is now disabled by default and a comment has been added to use `listings` when working offline without shell escape. This should make sure the template will not show any warnings when using the default (offline) installation of (Xe)LaTeX.

If you encounter any more errors, let me know!
