### ISSUE TITLE
reset spacing

### ISSUE THREAD

**Issue by albiboni** [dzwaneveld/tudelft-report-thesis-template#2]
From the description, I have read that you changed the spacing to make it tighter.
I would like to reset it to the original one, or increase it a bit below hline command. As you can see from the picture the text is almost attached to the line. Thank you in advance
![Screen Shot 2020-03-09 at 10 05 55](https://user-images.githubusercontent.com/22814582/76198129-c34d7c00-61ed-11ea-9a32-605df442c3d1.png)

**Comment by dzwaneveld** [comment]
Thanks for letting me know!

I have taken a look at the issue and was able to get the same result. Sadly, this is seems to be the default behavior (though it seems to be slightly worse with Arial compared to Computer Modern), nonetheless it can be fixed quite easily. 

If you would like to change the row spacing globally, simply add `\setlength\extrarowheight{2pt}` to the preamble (under 'Additional Commands' in `report.tex`). This command is part of the `array` package, which is a dependency of `tabularx` and should already be included in your class file. You can play around with the spacing, though 2pt seems pretty reasonable.

Another option is to use the `booktabs` package (already included in the class file). This package allows some more type lines, that also add slightly more spacing on default. The example below uses `\toprule`, `\midrule` and `\bottomrule` respectively. Depending on the type of table, also take a look at `\cmidrule(){}` if you want to take this route. 

![image](https://user-images.githubusercontent.com/51077132/76255425-70f07780-624e-11ea-9302-3cf68a834b2e.png)

If you would like to specifically address the height below the `\hline`, [this](https://tex.stackexchange.com/questions/202678/add-space-between-hline-and-superscript-without-affecting-any-other-spacing) or something like [this](https://tex.stackexchange.com/questions/207045/add-vertical-space-between-hline-and-the-row-consisting-of-only-multicolumn-w) might do the trick, thought I haven't used any of those solution myself before.

In the near future, I will also write some documentation for the template that will make sure that adjusting the template will be a bit more straight forward. Furthermore, it might also address some questions like this one.

I hope that was able to fix your problem. If you encounter anything else, let me know!
