### ISSUE TITLE
Dutch language support

### ISSUE THREAD

**Issue by FranseFrikandel** [dzwaneveld/tudelft-report-thesis-template#8]
Hello everyone!

As a TUDelft student, I absolutely love this template and use it in almost every project. I do sometimes run into having to use it in Dutch. Obviously translating most of the text to Dutch isn't too much of a hassle anyway, but I was wondering if there would be any interest in a PR to add support for Dutch into the template?

Looking into it, it seems it should be possible to change text based on the option selected for the babel package. For title pages etc. it might also be possible to simply include a Dutch template with the theme as well.

If there is interest in this, I will look into making a PR for it.

**Comment by dzwaneveld** [comment]
Great to hear you're finding this template useful! 

Adding support for Dutch has crossed my mind before (hence no hardcoded English in the class file anymore). You do have a valid point though, and it would be nice to make it even easier. 

As for the implementation, I am wondering what changes you suggest exactly. Just the inclusion of the babel package and translated title pages, or also other changes to translate titles such as the summary or references? There might be elegant ways to consider, but I am trying to keep the template as simple (and readable) as possible. 

Another option could be to include a FAQ entry in the documentation, which describes the process and provides alternative title pages to copy-and-paste. Finally, although I am not sure whether it would make sense, a translated branch might be something to consider (and of course providing an alternative 'Open in Overleaf' badge). 

I would be happy to hear your thoughts!

**Comment by FranseFrikandel** [comment]
What I found online is that it is possible to use which babel package was loaded and use that in if statements in LaTeX, however I hadn't realized there wasen't anything language specific in the class file. I think going for that in the report.tex file and other files would indeed only serve to make the template more complicated and harder to use, while the ease of use is exactly what makes this template so much more attractive than the official TUDelft one.

A extra branch I think will also make it unnecessarily complicated, with having to keep both branches up to date whenever anything gets changed. I think at this point the smartest thing might either be to just leave everything as is and leave the little translation work to the user, or to include sample title page files, and simply have commented out Dutch alternatives for the References and titles for for things like nomenclature.

**Comment by dzwaneveld** [comment]
Although a global `dutch` option is definitely feasible, I agree that the disadvantages would likely outweigh the advantages (especially when considering the scope and goal of this template).

Including translated title pages in the template would mean that there are four files to choose from. I think it would make more sense to add an entry to the FAQ in the documentation, describing the process (using `babel`) and providing translated title pages to download/copy-and-paste (e.g. `title-report-nl.tex`). That would mean only a few remaining chapter titles would have to be translated by the user.

If you really wanted, you could make a PR to the documentation. I would also be happy to make these changes. As I am currently busy studying, it will likely take a while either way. Thanks again for your suggestion. If you have any other suggestions, I would be happy to know!

**Comment by dzwaneveld** [comment]
Definitely has been a while! Ultimately, I have written a few instructions in the [FAQ](https://dzwaneveld.github.io/report/faq.html#using-the-template-in-dutch) about using the template in Dutch. Thanks for your suggestion! A link to translated title pages is something that could still be added there, but I have left it for now. Feel free to make a PR to the documentation. 

Let me know if you have any other suggestions, I would be happy to know!
