### ISSUE TITLE
Add support for externalizing tikz figures

### ISSUE THREAD

**Issue by meesfrensel** [dzwaneveld/tudelft-report-thesis-template#9]
Hi, thanks for this template. When trying to externalize figures with `\tikzexternalize`, the whole cover page and the TUD logo on the title page aren't showing. Adding the line below fixes that. Maybe that can be added to the template?

```latex
\tikzset{external/export next=false} % ADDED
\makecover

\input{00-title-page}

% ... in title page.tex:

\tikzset{external/export next=false} % ADDED
%% Insert the TU Delft logo at the bottom of the page
\begin{tikzpicture}[remember picture, overlay]
    \node[above=10mm] at (current page.south) { \includegraphics{figures/logo-black.pdf} };
\end{tikzpicture}
```

**Comment by dzwaneveld** [comment]
Thank you for your suggestion!

As more people could benefit from this suggestion, I do want to do something with this. At the same time, I feel hesitant to add commands to the template that are not relevant out-of-the-box. One of the main strengths of the template is the fact that it is relatively basic with minimal clutter. As such, I have decided to add this to the [FAQ](https://dzwaneveld.github.io/report/faq.html#externalizing-tikz-graphics) for now. In this way, I hope that externalizing Tikz graphics might even catch the attention of someone who was not aware of this possibility. 

Let me know if you have any other suggestions, I would be happy to know!

**Comment by meesfrensel** [comment]
That's a good compromise!
